from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from PIL import Image, ImageDraw, ImageFont
import json
import io
import random

def generate_presentation(json_content, extracted_images, temp_dir):
    """
    Generates a PowerPoint presentation from JSON content and extracted images.
    """
    # Parse JSON content (handle potential markdown code blocks)
    try:
        clean_json = json_content.replace('```json', '').replace('```', '').strip()
        data = json.loads(clean_json)
    except json.JSONDecodeError:
        # Fallback: try to find start and end of json object
        start = json_content.find('{')
        end = json_content.rfind('}') + 1
        if start != -1 and end != -1:
            clean_json = json_content[start:end]
            data = json.loads(clean_json)
        else:
            raise ValueError("Failed to parse AI response as JSON.")

    prs = Presentation()

    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = data.get("title", "Dental Presentation")
    subtitle.text = "Generated by AI Tool"

    # Content Slides
    # removed img_pool cycling to ensure relevance
    
    for i, slide_data in enumerate(data.get("slides", [])):
        try:
             # Use "Title and Content" layout (index 1)
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            
            # --- 1. Handle Title ---
            title_shape = slide.shapes.title
            title_shape.text = slide_data.get("title", "Untitled Slide")
            
            # --- 2. Handle Content & Layout Strategy ---
            # Default: Text takes up full width (mostly)
            body_shape = slide.shapes.placeholders[1]
            
            # Select Image (Strict relevance check)
            current_img_path = None
            
            # Check if AI expects a specific image index
            suggested_index = slide_data.get("suggested_image_index", -1)
            suggested_type = slide_data.get("suggested_image_type", "generic").lower()
            
            # 1. SPECIFIC IMAGE INDEX (Higher Priority)
            if suggested_index >= 0 and suggested_index < len(extracted_images):
                img_info = extracted_images[suggested_index]
                current_img_path = img_info["path"]
                
            # 2. GENERIC TYPE REQUEST (Fallback / Auto-Flow)
            elif suggested_type not in ["generic", "none", "text_only"] and extracted_images:
                # Find the next available image that hasn't been used explicitly?
                # For now, simplistic approach: Pop the first one IF index wasn't used.
                # Ideally we track usage, but popping is safer for simple flows.
                if len(extracted_images) > 0:
                     img_info = extracted_images.pop(0) 
                     current_img_path = img_info["path"]

            # --- 3. Apply Layout based on Layout Type & Image Existence ---
            layout_type = slide_data.get("layout", "standard")
            
            if layout_type == "results_slide" and current_img_path:
                # --- RESULTS LAYOUT: Maximized Image ---
                # Image takes center stage (80% width)
                img_left = Inches(1.0)
                img_top = Inches(1.5)
                img_width = Inches(8.0)
                # Let height adjust automatically or cap it?
                # slide.shapes.add_picture(current_img_path, img_left, img_top, width=img_width)
                
                # Better: Add picture and restrict height to avoid overflow
                pic = slide.shapes.add_picture(current_img_path, img_left, img_top, width=img_width)
                if pic.height > Inches(5.0):
                    pic.height = Inches(5.0)
                    pic.left = Inches(10 - (pic.width.inches))/2 # Re-center if width changed
                
                # Text as Caption below
                if slide_data.get("content"):
                    caption_box = slide.shapes.add_textbox(Inches(0.5), Inches(6.6), Inches(9.0), Inches(1.0))
                    tf = caption_box.text_frame
                    tf.word_wrap = True
                    p = tf.add_paragraph()
                    p.text = slide_data["content"][0] # Use first bullet as main caption
                    p.font.size = Pt(14)
                    p.font.bold = True
                    p.alignment = 2 # Center

            elif layout_type == "procedure_slide" and current_img_path:
                # --- PROCEDURE LAYOUT: Side-by-Side Images ---
                
                # Try to fetch a second image for comparison/steps
                img2_path = None
                if extracted_images:
                    # simplistic: take next available
                    img2_path = extracted_images.pop(0)["path"]

                # Image 1 (Left)
                pic1 = slide.shapes.add_picture(current_img_path, Inches(0.5), Inches(1.5), width=Inches(4.25))
                if pic1.height > Inches(4.0): pic1.height = Inches(4.0)

                # Image 2 (Right) - If available
                if img2_path:
                    pic2 = slide.shapes.add_picture(img2_path, Inches(5.0), Inches(1.5), width=Inches(4.25))
                    if pic2.height > Inches(4.0): pic2.height = Inches(4.0)
                
                # Text Description Below
                textBox = slide.shapes.add_textbox(Inches(0.5), Inches(5.6), Inches(9.0), Inches(1.5))
                tf = textBox.text_frame
                tf.word_wrap = True
                for point in slide_data.get("content", []):
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 0
                    p.font.size = Pt(14)

            elif current_img_path:
                # --- STANDARD IMAGE LAYOUT ---
                # Text on Left (55%), Image on Right (45%)
                
                # Resize Text Box
                body_shape.left = Inches(0.5)
                body_shape.top = Inches(1.5)
                body_shape.width = Inches(5.0) 
                body_shape.height = Inches(5.0)
                
                # Populate Text (Standard)
                tf = body_shape.text_frame
                tf.clear()
                for point in slide_data.get("content", []):
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 0
                    p.font.size = Pt(18)
                    p.space_after = Pt(10)

                # Add Image to the Right
                try:
                    max_img_width = Inches(4.0)
                    img_left = Inches(5.7)
                    img_top = Inches(1.5)
                    slide.shapes.add_picture(current_img_path, img_left, img_top, width=max_img_width)
                except Exception as e:
                    print(f"Could not add image {current_img_path}: {e}")

            else:
                # --- TEXT ONLY LAYOUT ---
                body_shape.left = Inches(0.5)
                body_shape.top = Inches(1.5)
                body_shape.width = Inches(9.0)
                body_shape.height = Inches(5.0)
                
                # Populate Text
                tf = body_shape.text_frame
                tf.clear()
                for point in slide_data.get("content", []):
                    p = tf.add_paragraph()
                    p.text = point
                    p.level = 0
                    p.font.size = Pt(24) # Larger text for text-only
                    p.space_after = Pt(10)

            # --- 5. Add Reference Footer ---
            if "reference" in slide_data:
                left = Inches(0.5)
                top = Inches(6.8) # Near bottom
                width = Inches(9.0)
                height = Inches(0.5)
                txBox = slide.shapes.add_textbox(left, top, width, height)
                tf_ref = txBox.text_frame
                p_ref = tf_ref.add_paragraph()
                p_ref.text = f"Ref: {slide_data['reference']}"
                p_ref.font.size = Pt(10)
                p_ref.font.italic = True
                p_ref.font.color.rgb = None # Default theme color or gray

            # --- 6. Add Speaker Notes ---
            if "notes" in slide_data:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = slide_data["notes"]
                
        except Exception as e:
            print(f"Skipping slide due to error: {e}")

    # Save to buffer
    output_io = io.BytesIO()
    prs.save(output_io)
    output_io.seek(0)
    return output_io

def create_instagram_post(content, logo_stream=None, ref_image_stream=None, title="New Research"):
    """
    Creates a 10x10 inch Instagram square post.
    """
    prs = Presentation()
    # Square Format (10x10 inches)
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(10)
    
    slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank
    
    # --- DESIGN CONSTANTS ---
    BG_COLOR = RGBColor(255, 255, 255) # White
    ACCENT_COLOR = RGBColor(0, 51, 102) # Navy
    TEXT_COLOR = RGBColor(51, 51, 51) # Dark Gray
    
    # Background
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = BG_COLOR
    
    # --- 1. HEADER (Title) ---
    # Large, impactful title at top
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(2))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title.upper()
    p.font.size = Pt(44)
    p.font.bold = True
    p.font.color.rgb = ACCENT_COLOR
    p.alignment = PP_ALIGN.CENTER
    
    current_y = Inches(2.5)
    
    # --- 2. MAIN VISUAL (Center) ---
    # Prioritize Reference Image or Logo if no ref image
    if ref_image_stream:
        try:
            # Add Image centered
            img_height = Inches(4.5)
            # Center calculation: Slide Width (10) - Image Width (assume square-ish or fit)
            # We'll just place it and let aspect ratio handle width
            pic = slide.shapes.add_picture(ref_image_stream, Inches(1), current_y, height=img_height)
            
            # Center the image horizontally
            pic.left = int((prs.slide_width - pic.width) / 2)
            current_y += img_height + Inches(0.5)
            
        except Exception as e:
            print(f"Error adding ref image: {e}")
            
    elif logo_stream and not ref_image_stream:
        # If only logo, make it big in center? No, logo usually top/bottom.
        # Let's just leave space or use a placeholder shape if no image
        pass

    # --- 3. TEXT CONTENT (Bullets) ---
    # "Key Takeaways" or promotional bullets
    body_box = slide.shapes.add_textbox(Inches(1), current_y, Inches(8), Inches(2.5))
    tf = body_box.text_frame
    tf.word_wrap = True
    
    # Add content bullets
    for key, value in content.items():
        # content is likely {"Headline": "...", "Key Points": "..."}
        # Flatten distinct keys into paragraphs
        if isinstance(value, str):
            p = tf.add_paragraph()
            p.text = f"• {value}"
            p.font.size = Pt(20)
            p.font.color.rgb = TEXT_COLOR
            p.space_after = Pt(10)
        elif isinstance(value, list):
            for item in value:
                p = tf.add_paragraph()
                p.text = f"• {item}"
                p.font.size = Pt(20)
                p.font.color.rgb = TEXT_COLOR
                p.space_after = Pt(10)

    # --- 4. LOGO (Bottom Right or Top Corner) ---
    if logo_stream:
        try:
            # Bottom Right branding
            logo_height = Inches(1.0)
            slide.shapes.add_picture(logo_stream, Inches(8.5), Inches(8.5), height=logo_height)
        except Exception as e:
            # If stream was consumed, might fail if not reset.
            # But here we distinct streams or re-seek if reused (handled in app.py)
            pass

    # Save
    out = io.BytesIO()
    prs.save(out)
    out.seek(0)
    return out

def create_poster(content, logo_stream=None, ref_image_stream=None, title="Scientific Poster"):
    """
    Creates a 48x36 inch scientific poster.
    """
    prs = Presentation()
    # Set Slide Size to 48x36 inches (Standard Landscape Poster)
    prs.slide_width = Inches(48)
    prs.slide_height = Inches(36)
    
    slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout
    
    # --- DESIGN CONSTANTS ---
    # Colors
    HEADER_BG = RGBColor(0, 51, 102) # Navy Blue
    HEADER_TEXT = RGBColor(255, 255, 255) # White
    COL_BG = RGBColor(240, 248, 255) # AliceBlue
    
    # Dimensions
    MARGIN = Inches(1)
    HEADER_HEIGHT = Inches(5)
    COL_GAP = Inches(1)
    
    # 3-Column Layout
    NUM_COLS = 3
    COL_WIDTH = (prs.slide_width - (MARGIN * 2) - (COL_GAP * (NUM_COLS - 1))) / NUM_COLS
    COL_HEIGHT = prs.slide_height - HEADER_HEIGHT - (MARGIN * 2)
    
    # --- 1. HEADER SECTION ---
    header_shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, HEADER_HEIGHT)
    header_shape.fill.solid()
    header_shape.fill.fore_color.rgb = HEADER_BG
    header_shape.line.color.rgb = HEADER_BG
    
    # Title
    title_box = slide.shapes.add_textbox(MARGIN, Inches(0.5), prs.slide_width - (MARGIN*2), Inches(2.5))
    tf = title_box.text_frame
    p = tf.paragraphs[0]
    p.text = title.upper()
    p.font.size = Pt(80)
    p.font.bold = True
    p.font.color.rgb = HEADER_TEXT
    p.alignment = PP_ALIGN.CENTER
    
    # Subtitle / Authors
    sub_box = slide.shapes.add_textbox(MARGIN, Inches(3), prs.slide_width - (MARGIN*2), Inches(1.5))
    tf_sub = sub_box.text_frame
    p_sub = tf_sub.paragraphs[0]
    p_sub.text = "Generated by AI Research Assistant | Department of Innovative Dentistry"
    p_sub.font.size = Pt(40)
    p_sub.font.color.rgb = HEADER_TEXT
    p_sub.alignment = PP_ALIGN.CENTER
    
    # Logo (Top Left/Right)
    if logo_stream:
        try:
            # Add Logo (Left)
            logo_height = Inches(3.5)
            slide.shapes.add_picture(logo_stream, Inches(1), Inches(0.75), height=logo_height)
        except Exception as e:
            print(f"Error adding logo: {e}")

    # --- 2. CONTENT COLUMNS ---
    # We will distribute content into 3 columns:
    # Col 1: Introduction, Aims
    # Col 2: Methods, Visuals (Ref Image)
    # Col 3: Results, Conclusion, References
    
    # Define Column Positions
    col_x_positions = [MARGIN, MARGIN + COL_WIDTH + COL_GAP, MARGIN + (COL_WIDTH + COL_GAP) * 2]
    
    # Content Mapping (Simple distribution)
    # content is a dict: {'Introduction': text, 'Methods': text, ...}
    
    sections = list(content.keys())
    
    # Helper to add section box
    def add_section(col_idx, current_y, title, body_text):
        # Title Box
        t_box = slide.shapes.add_textbox(col_x_positions[col_idx], current_y, COL_WIDTH, Inches(1.5))
        t_p = t_box.text_frame.paragraphs[0]
        t_p.text = title.upper()
        t_p.font.size = Pt(40)
        t_p.font.bold = True
        t_p.font.color.rgb = HEADER_BG
        
        # Body Box
        b_box = slide.shapes.add_textbox(col_x_positions[col_idx], current_y + Inches(1.2), COL_WIDTH, Inches(1))
        # Text wrapping and sizing
        tf = b_box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = body_text
        p.font.size = Pt(28)
        
        # Estimate height used (very rough)
        # Assuming ~50 chars per line, 28pt font (~0.4 inch line height)
        lines = len(body_text) / 40
        height_used = Inches(1.5) + (Pt(35) * lines) + Inches(1)
        return height_used
    
    # COL 1
    curr_y = HEADER_HEIGHT + Inches(1)
    for sec in ['Introduction', 'Background', 'Aims', 'Objectives']:
        if sec in content:
            used = add_section(0, curr_y, sec, content[sec])
            curr_y += used
            
    # COL 2 (Methods + Visuals)
    curr_y = HEADER_HEIGHT + Inches(1)
    
    # VISUALS FIRST in Col 2 (Centerpiece)
    if ref_image_stream:
        try:
            img_width = COL_WIDTH
            slide.shapes.add_picture(ref_image_stream, col_x_positions[1], curr_y, width=img_width)
            curr_y += Inches(10) # Placeholder height for image, auto-scaled usually but need generic spacer
        except Exception as e:
            print(f"Error adding ref image: {e}")
            
    for sec in ['Methods', 'Methodology', 'Materials']:
        if sec in content:
            used = add_section(1, curr_y, sec, content[sec])
            curr_y += used

    # COL 3
    curr_y = HEADER_HEIGHT + Inches(1)
    for sec in ['Results', 'Discussion', 'Conclusion', 'References']:
        if sec in content:
            used = add_section(2, curr_y, sec, content[sec])
            curr_y += used

    # Save
    out = io.BytesIO()
    prs.save(out)
    out.seek(0)
    return out

def create_instagram_image(content, logo_stream=None, ref_image_stream=None, title="New Research"):
    """
    Creates a 1080x1080 JPEG image for Instagram.
    """
    import textwrap
    
    # 1. Setup Canvas
    WIDTH, HEIGHT = 1080, 1080
    bg_color = (255, 255, 255) # White
    img = Image.new('RGB', (WIDTH, HEIGHT), color=bg_color)
    draw = ImageDraw.Draw(img)
    
    # Colors
    NAVY = (0, 51, 102)
    WHITE = (255, 255, 255)
    BLACK = (50, 50, 50)
    
    # Fonts
    try:
        font_title = ImageFont.truetype("arial.ttf", 60)
        font_body = ImageFont.truetype("arial.ttf", 40)
        font_small = ImageFont.truetype("arial.ttf", 30)
    except:
        font_title = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_small = ImageFont.load_default()

    # 2. Header (Top Bar)
    header_height = 150
    draw.rectangle([(0, 0), (WIDTH, header_height)], fill=NAVY)
    
    # Draw Title Centered
    # Wrap title if too long
    title_lines = textwrap.wrap(title.upper(), width=30)
    y_text = 40
    for line in title_lines:
        # Calculate text size (bbox)
        bbox = draw.textbbox((0, 0), line, font=font_title)
        text_w = bbox[2] - bbox[0]
        x_text = (WIDTH - text_w) / 2
        draw.text((x_text, y_text), line, font=font_title, fill=WHITE)
        y_text += 70 # Line spacing
        if y_text > header_height - 20: break # detailed breakdown not possible if title huge
        
    current_y = header_height + 50
    
    # 3. Main Image (Reference)
    if ref_image_stream:
        try:
            ref_img = Image.open(ref_image_stream)
            # Resize logic: Max width 900, Max Height 500
            ref_img.thumbnail((900, 500))
            
            # Center it
            img_w, img_h = ref_img.size
            x_pos = (WIDTH - img_w) // 2
            img.paste(ref_img, (x_pos, current_y))
            current_y += img_h + 50
        except Exception as e:
            print(f"Error processing ref image: {e}")
            
    elif logo_stream and not ref_image_stream:
         # Fallback to logo if no ref image
         pass

    # 4. Text Content
    # We expect content to be a dict or list for bullets
    margin = 80
    
    # Flatten content
    bullets = []
    if isinstance(content, dict):
        for k, v in content.items():
            if isinstance(v, list): bullets.extend(v)
            else: bullets.append(str(v))
    
    for bullet in bullets:
        # Wrap text
        lines = textwrap.wrap(f"• {bullet}", width=50) # Approx chars for 40px font
        for line in lines:
            if current_y > HEIGHT - 150: break # Stop if out of space
            draw.text((margin, current_y), line, font=font_body, fill=BLACK)
            current_y += 50
        current_y += 20 # Extra space between bullets
        
    # 5. Logo (Bottom Right)
    if logo_stream:
        try:
            # Need to re-open or if it was consumed, seek 0?
            # It's a BytesIO, so we should allow re-reading if not closed
            # But PIL Image.open usually needs a fresh stream or valid position.
            # Assuming caller handles stream position or provides fresh.
            if logo_stream.tell() > 0: logo_stream.seek(0)
            
            logo = Image.open(logo_stream)
            logo.thumbnail((200, 100))
            logo_w, logo_h = logo.size
            img.paste(logo, (WIDTH - logo_w - 30, HEIGHT - logo_h - 30), logo if logo.mode=='RGBA' else None)
        except Exception as e:
            print(f"Error adding logo to JPG: {e}")

    # Return JPEG
    output = io.BytesIO()
    img.save(output, format='JPEG', quality=95)
    output.seek(0)
    return output
